CCL-WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CCL_WEB.Models;
using CCL_WEB.Helpers;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace CCL_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly CCLdbContext context;
        private HomeHelper homeHelper;

        public HomeController(ILogger<HomeController> logger, CCLdbContext context)
        {
            _logger = logger;
            this.context = context;
            homeHelper = new HomeHelper(context);
        }

        //GET: '/'
        public IActionResult Index()
        {
            ListingViewModel mv = new ListingViewModel();
            var years = context.Year.Distinct().OrderBy(m => m.Value).ToList();
            foreach (var y in years)
            {
                if (y.Value.Length > 4 || y.Value.Equals("9831"))
                {
                    
                }
                else
                 mv.Years.Add(new SelectListItem { Text = y.Value, Value = y.Value });
            }
            return View(mv);
        }

        //Post
        [HttpPost]
        public IActionResult Index(string year, string make, string model, int? page)
        {
            ListingViewModel mv = new ListingViewModel();
            var years = context.Year.Distinct().OrderByDescending(m => m.Value).ToList();
            foreach (var y in years)
            {
                mv.Years.Add(new SelectListItem { Text = y.Value, Value = y.Value });
            }

            if (year != null)
            {
                var makes = context.make.Where(m => m.Year.Equals(year)).Distinct().OrderBy(m => m.Value).ToList();
                foreach (var m in makes)
                {
                    mv.Makes.Add(new SelectListItem { Text = m.Value, Value = m.Value });
                }
            }

            if (make != null)
            {
                var models = context.model.Where(m => m.Make.Equals(make)).Distinct().OrderBy(m => m.Value).ToList();
                List<string> modelList = new List<string>();

                foreach (var m in models)
                {
                   if (!modelList.Contains(m.Value))
                    {
                        modelList.Add(m.Value);
                        mv.Models.Add(new SelectListItem { Text = m.Value, Value = m.Value });
                    }
                }
                    
            }
            if (model != null)
            {
                var pageNumber = page ?? 1;
                int pageSize = 25;
                var listings = context.Listing.Where(m => m.Year.Equals(year) && m.Make.Equals(make) && m.Model.Equals(model)).ToList();
                mv.Listings.AddRange(listings);
                //return RedirectToAction("Index", "Listing", listings);
            }
            return View(mv);
           
        }

        public IActionResult Success(List<Listing> listings)
        {
            return View(listings);
        }

        [HttpGet]
        public JsonResult GetMakes(string year)
        {
            return Json(new SelectList(context.make.Where(m => m.Year.Equals(year)), "Id", "Year"));
        }

        public IActionResult Models(string make)
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public List<Listing> GetYear()
        {
            List<Listing> years = context.Listing.ToList();
            return years;
        }

    }
}

CCL-WEB/Controllers/SingleListingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCL_WEB.Helpers;
using CCL_WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace CCL_WEB.Controllers
{
    public class SingleListingController : Controller
    {
        private readonly CCLdbContext context;
        private ListingHelper listingHelper;

        public SingleListingController(CCLdbContext context)
        {
            this.context = context;
            listingHelper = new ListingHelper(context);
        }
        //GET: '/SingleListing'
        public IActionResult Index(int? id)
        {
            var listing = context.Listing.Find(id);
            return View(listing);
        }

        public IActionResult GoToDealerSite(string[] listing)
        {
            //this will add the dealer to the database and set a timestamp when the user clicks the dealer url link
            string stockNum = "103555";
            string dealerUrl = "https://www.gtautolounge.com/classic-cars-sacramento?searchfor=YearMakeModel&searchtext=" + stockNum + "&inventorysearch=1";

            var dealer = new Dealer
            {
                ListingId = listing[0],
                DealerName = listing[1],
                DealerUrl = listing[2],
                DateVisited = DateTime.Now
            };
            context.Dealer.Add(dealer);
            context.SaveChanges();

            return Redirect(listing[2]);
        }
    }
}

CCL-WEB/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

CCL-WEB/Views/Home/Index.cshtml
@model CCL_WEB.Models.ListingViewModel
@{
    ViewData["Title"] = "Home Page";
}
<div class="container mt-100">
    <section style="border-radius: 22px;">
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-bg-warning formControl-shadow-1-2-50">
                    <form asp-controller="Home" asp-action="Index" method="post" name="formSearch">
                        <div class="card-body">
                            <div class="card-title text-center">Search Query</div>
                            <div class="col-sm-12">
                                <p class="mb-1">
                                    @Html.DropDownListFor(m => m.Year, Model.Years, "--Select Year--", new {onchange = "document.forms[0].submit()",  @class = "form-control" })
                                  
                                </p>
                                <p class="mb-1">
                                    @Html.DropDownListFor(m => m.Make, Model.Makes, "--Select Make--", new { onchange = "document.forms[0].submit()", disabled = "disabled", @class = "form-control" })
                                   
                                </p>
                                <p class="mb-1">
                                    @Html.DropDownListFor(m => m.Model, Model.Models, "--Select Model--", new {disabled = "disabled", @class = "form-control" })
                                    
                                </p>
                                <input type="submit" Value="Submit" class="btn btn-primary btn-shadow-1 mb-2 mt-2" />
                            </div>
                        </div>
                    </form>
                </div>
                <!--End Card-->
            </div>
        </div>
        <div class="row mt-20">
            <div class="col-sm-12">
                <div class=" alert alert-warning text-dark box-shadow-2">Use the above form to search for classic cars by Year, Make and Model</div>
            </div>
        </div>
    </section>

    <section class="container">
        @if (Model != null)
        {
            if (Model.Listings.Count < 1)
            {
                <div id="queryResult" class="alert alert-dark mt-5 box-shadow-1">
                    Your query return 0 results. Either there are 0 Listings or your query was in the wrong format.
                </div>
            }
            else
            {
                <div class="alert alert-dark mt-5 box-shadow-1">
                    Your query return @Model.Listings.Count results.
                </div>
                <div class="row mt-5">

                    @foreach (var listing in Model.Listings)
                    {

                        <div class="card formControl-shadow-2-2-50 card-bg-light-grey-dark-grey mb-3 align-content-center p-2">
                            <div class="row no-gutters">
                                <div class="col-sm-4 flex">
                                    @if (listing.MainImgUrl == null)
                                    {
                                        <label>no image available</label>
                                    }
                                    else
                                    {
                                        <img src="@Url.Content(listing.MainImgUrl)" class="card-img align-content-center box-shadow-2 mt-3" alt="...">
                                    }

                                </div>
                                <div class="col-sm-8">
                                    <div class="card-body">
                                        <h6 class="card-subtitle text-black-50 ml-1">@listing.ListingId</h6>
                                        <h5 class="card-title text-warning text-shadow-1-2-50 ml-1">@listing.Title</h5>
                                        <table>
                                            <tbody>
                                                <tr><td class="ml-2">@listing.Location</td></tr>
                                                <tr><td class="ml-2 text-warning text-shadow-1-2-50"><strong>Price:&nbsp;@listing.Price</strong></td></tr>
                                                <tr><td class="ml-2">Make:&nbsp;@listing.Make</td></tr>
                                                <tr><td class="ml-2">Model:&nbsp;@listing.Model</td></tr>
                                                <tr><td class="ml-2">Year&nbsp;@listing.Year</td></tr>
                                                <tr><td class="mt-5 ml-2">
                                                        @if (listing.DealerUrl != "" || listing.DealerUrl != null)
                                                        {
                                                            <a class="btn btn-dark text-shadow" role="button" asp-controller="SingleListing" asp-action="Index" asp-route-id="@listing.Id">Details</a>
                                                        }
                                                </td></tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }

                </div>
            }

        }
    </section>
</div>
<script src="../../lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(function () {
        if ($("#Year option").length > 1) {
            $("#Make").removeAttr("disabled");
        }
        if ($("#Make option").length > 1) {
            $("#Model").removeAttr("disabled");
        }
        
    });
</script>

CCL-WEB/Views/Home/Success.cshtml
@model IEnumerable<CCL_WEB.Models.Listing>

@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ListingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Transmission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Engine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DealerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DealerUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MainImgUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ListingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Transmission)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Engine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DealerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DealerUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MainImgUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
        </tr>
}
    </tbody>
</table>